import environ

environ.Env.read_env(env_file=(environ.Path(__file__) - 2)(".env"))

env = environ.Env(
    SECRET_KEY=(str, "SK"),
    DEBUG=(bool, False),
    ALLOWED_HOSTS=(lambda v: [s.strip() for s in v.split(",")], list("*")),
    DEFAULT_DATABASE=(str, "sqlite:///db.sqlite3"),
    CELERY_BROKER_URL=(str, "redis://localhost:6379/0"),
    REDIS_URL=(str, "redis://localhost:6379/1"),
    REDIS_CHANNEL_URL=(str, "redis://localhost:6379/1"),
    SQS_MESSAGES_QUEUE_URL=(str, ""),
    SQS_ROOMS_QUEUE_URL=(str, ""),
    SQS_CONVERSATION_DLQ_URL=(str, ""),
    SQS_CONVERSATION_REGION=(str, "us-east-1"),
    SQS_BILLING_QUEUE_URL=(str, ""),
    DYNAMODB_MESSAGE_TABLE=(str, ""),
    DYNAMODB_REGION=(str, "us-east-1"),
    USE_SENTRY=(bool, False),
    SENTRY_URL=(str, ""),
    ENVIRONMENT=(str, "development"),
    FILTER_SENTRY_EVENTS=(list, []),
    # Data Lake SDK (for CSAT/NPS)
    AGENT_UUID_CSAT=(str, ""),
    AGENT_UUID_NPS=(str, ""),
    JWT_PUBLIC_KEY=(str, ""),
    OIDC_OP_TOKEN_ENDPOINT=(str, ""),
    OIDC_RP_CLIENT_ID=(str, ""),
    OIDC_RP_CLIENT_SECRET=(str, ""),
    IMPROVEMENTS_BATCH_CHECK_TIMEOUT_SECONDS=(int, 86400),
    CONVERSATION_RETENTION_DAYS=(int, 90),
    CONVERSATION_ARCHIVE_ENABLED=(bool, False),
    CONVERSATION_ARCHIVE_DRY_RUN=(bool, True),
    CONVERSATION_ARCHIVE_S3_BUCKET=(str, ""),
    CONVERSATION_ARCHIVE_S3_PREFIX=(str, "conversations-archive"),
    CONVERSATION_ARCHIVE_S3_REGION=(str, ""),
    CONVERSATION_ARCHIVE_LOCK_ENABLED=(bool, True),
    CONVERSATION_ARCHIVE_LOCK_TTL_SECONDS=(int, 7200),
    CONVERSATION_ARCHIVE_BATCH_SIZE=(int, 500),
    CONVERSATION_ARCHIVE_CELERY_QUEUE=(str, "conversations-archive"),
    CONVERSATION_ARCHIVE_TASK_EXPIRES_SECONDS=(int, 3600),
    CONVERSATION_ARCHIVE_WINDOW_START_HOUR=(int, None),
    CONVERSATION_ARCHIVE_WINDOW_END_HOUR=(int, None),
)
