import environ

environ.Env.read_env(env_file=(environ.Path(__file__) - 2)(".env"))

env = environ.Env(
    SECRET_KEY=(str, "SK"),
    DEBUG=(bool, False),
    ALLOWED_HOSTS=(lambda v: [s.strip() for s in v.split(",")], list("*")),
    DEFAULT_DATABASE=(str, "sqlite:///db.sqlite3"),
    CELERY_BROKER_URL=(str, "redis://localhost:6379/0"),
    REDIS_URL=(str, "redis://localhost:6379/1"),
    REDIS_CHANNEL_URL=(str, "redis://localhost:6379/1"),
    SQS_MESSAGES_QUEUE_URL=(str, ""),
    SQS_ROOMS_QUEUE_URL=(str, ""),
    SQS_CONVERSATION_DLQ_URL=(str, ""),
    SQS_CONVERSATION_REGION=(str, "us-east-1"),
    SQS_BILLING_QUEUE_URL=(str, ""),
    DYNAMODB_MESSAGE_TABLE=(str, ""),
    DYNAMODB_REGION=(str, "us-east-1"),
    USE_SENTRY=(bool, False),
    SENTRY_URL=(str, ""),
    ENVIRONMENT=(str, "development"),
    FILTER_SENTRY_EVENTS=(list, []),
    APM_DISABLE_SEND=(bool, True),
    APM_SECRET_TOKEN=(str, ""),
    APM_SERVER_URL=(str, ""),
    APM_SERVICE_DEBUG=(bool, False),
    APM_SERVICE_NAME=(str, "nexus-conversations"),
    # Data Lake SDK (for CSAT/NPS)
    AGENT_UUID_CSAT=(str, ""),
    AGENT_UUID_NPS=(str, ""),
    JWT_PUBLIC_KEY=(str, ""),
    OIDC_OP_TOKEN_ENDPOINT=(str, ""),
    OIDC_RP_CLIENT_ID=(str, ""),
    OIDC_RP_CLIENT_SECRET=(str, ""),
    IMPROVEMENTS_BATCH_CHECK_TIMEOUT_SECONDS=(int, 86400),
    IMPROVEMENTS_LAMBDA_READ_TIMEOUT_SECONDS=(int, 300),
    CORS_ORIGIN_ALLOW_ALL=(bool, False),
    CORS_ALLOWED_ORIGINS=(list, []),
    CORS_ALLOW_CREDENTIALS=(bool, False),
)
