import environ

environ.Env.read_env(env_file=(environ.Path(__file__) - 2)(".env"))

env = environ.Env(
    SECRET_KEY=(str, "SK"),
    DEBUG=(bool, False),
    ALLOWED_HOSTS=(lambda v: [s.strip() for s in v.split(",")], list("*")),
    DEFAULT_DATABASE=(str, "sqlite:///db.sqlite3"),
    CELERY_BROKER_URL=(str, "redis://localhost:6379/0"),
    REDIS_URL=(str, "redis://localhost:6379/1"),
    REDIS_CHANNEL_URL=(str, "redis://localhost:6379/1"),
    SQS_MESSAGES_QUEUE_URL=(str, ""),
    SQS_ROOMS_QUEUE_URL=(str, ""),
    SQS_CONVERSATION_DLQ_URL=(str, ""),
    SQS_CONVERSATION_REGION=(str, "us-east-1"),
    SQS_BILLING_QUEUE_URL=(str, ""),
    DYNAMODB_MESSAGE_TABLE=(str, ""),
    DYNAMODB_REGION=(str, "us-east-1"),
    USE_SENTRY=(bool, False),
    SENTRY_URL=(str, ""),
    ENVIRONMENT=(str, "development"),
    FILTER_SENTRY_EVENTS=(list, []),
    # Data Lake SDK (for CSAT/NPS)
    AGENT_UUID_CSAT=(str, ""),
    AGENT_UUID_NPS=(str, ""),
    PROJECT_COUNT_THRESHOLD=(int, 100),
    USE_EDA=(bool, False),
    EDA_BROKER_HOST=(str, ""),
    EDA_BROKER_PORT=(int, 5671),
    EDA_BROKER_USER=(str, ""),
    EDA_BROKER_PASSWORD=(str, ""),
    EDA_VIRTUAL_HOST=(str, "/"),
    EDA_PROJECT_COUNT_EXCHANGE=(str, ""),
    PIKA_EDA_BROKER_HOST=(str, ""),
    PIKA_EDA_BROKER_PORT=(int, 5671),
    PIKA_EDA_BROKER_USER=(str, ""),
    PIKA_EDA_BROKER_PASSWORD=(str, ""),
    PIKA_EDA_VIRTUAL_HOST=(str, "/"),
    PIKA_EDA_SSL_ENABLED=(bool, True),
    PIKA_EDA_HEARTBEAT=(int, 600),
    PIKA_EDA_BLOCKED_CONNECTION_TIMEOUT=(int, 300),
    JWT_PUBLIC_KEY=(str, ""),
)
