CLOSE_DAILY_PROJECT_CHUNK = 100

SYNC_PROJECT_TIMEZONES_LOCK_KEY = "conversation_ms:sync_project_timezones_active"
SYNC_PROJECT_TIMEZONES_LOCK_TTL_SECONDS = 7200

CLOSE_DAILY_LOCK_KEY = "conversation_ms:close_daily_active"

CLOSE_DAILY_PROJECT_LOCK_KEY_PREFIX = "conversation_ms:close_daily_project:"

RESOLUTION_IN_PROGRESS = "2"
TERMINAL_RESOLUTIONS = frozenset({"0", "1", "3", "4"})

CLOSE_PIPELINE_STAGES = ("classify", "topics", "billing", "datalake")

# Separate Celery queues for observability; same conversations-celery pod consumes all via -Q.
CLOSE_PIPELINE_QUEUE_LAMBDA = "close_lambda"
CLOSE_PIPELINE_QUEUE_BILLING = "close_billing"
CLOSE_PIPELINE_QUEUE_DATALAKE = "close_datalake"

CLOSE_PIPELINE_CLASSIFY_MAX_RETRIES = 3
CLOSE_PIPELINE_TOPICS_MAX_RETRIES = 3
CLOSE_PIPELINE_BILLING_MAX_RETRIES = 5
CLOSE_PIPELINE_DATALAKE_MAX_RETRIES = 5

CLOSE_PIPELINE_STAGE_RETRY_DELAY_SECONDS = 60
CLOSE_PIPELINE_LAMBDA_SOFT_TIME_LIMIT_SECONDS = 300
CLOSE_PIPELINE_LAMBDA_TIME_LIMIT_SECONDS = 360
CLOSE_PIPELINE_SIDEEFFECT_SOFT_TIME_LIMIT_SECONDS = 120
CLOSE_PIPELINE_SIDEEFFECT_TIME_LIMIT_SECONDS = 180

CLOSE_PIPELINE_DRAIN_SOFT_TIME_LIMIT_SECONDS = 240
CLOSE_PIPELINE_DRAIN_TIME_LIMIT_SECONDS = 300

CLOSE_PIPELINE_PENDING_HEARTBEAT_SECONDS_DEFAULT = 600
CLOSE_PIPELINE_STALE_PENDING_SECONDS_DEFAULT = 1800
CLOSE_PIPELINE_MAX_DRAIN_RECLAIMS_DEFAULT = 5
CLOSE_PIPELINE_DRAIN_BATCH_SIZE_DEFAULT = 100
CLOSE_PIPELINE_BILLING_OUTAGE_PAUSE_DEFAULT = False

CLOSE_PIPELINE_DEAD_BUDGET_EXHAUSTED = "drain reclaim budget exhausted"


class ClosePipelineStageStatus:
    PENDING = "pending"
    DONE = "done"
    SKIPPED = "skipped"
    FAILED = "failed"
    DEAD = "dead"

    CHOICES = (
        (PENDING, "Pending"),
        (DONE, "Done"),
        (SKIPPED, "Skipped"),
        (FAILED, "Failed"),
        (DEAD, "Dead"),
    )

    ALL = frozenset({PENDING, DONE, SKIPPED, FAILED, DEAD})
    FINISHED = frozenset({DONE, SKIPPED})
    TERMINAL = frozenset({DONE, SKIPPED, FAILED, DEAD})


class CloseDatalakeEventKind:
    CLASSIFICATION = "classification"
    TOPICS = "topics"

    CHOICES = (
        (CLASSIFICATION, "Classification"),
        (TOPICS, "Topics"),
    )

    ALL = frozenset({CLASSIFICATION, TOPICS})
