# Generated by Django 4.2.27 on 2026-06-16 18:45

import uuid

import django.db.models.deletion
from django.db import migrations, models

import improvements.utils.time


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("conversation_ms", "0006_project_timezone"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImprovementAnalysisRun",
            fields=[
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("target_date", models.DateField()),
                ("triggered_on_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("building", "Building"),
                            ("polling", "Polling"),
                            ("in_progress", "In progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="queued",
                        max_length=32,
                    ),
                ),
                ("sampling_mode", models.CharField(default="srs", max_length=64)),
                ("population_n", models.PositiveIntegerField(default=0)),
                ("sample_size", models.PositiveIntegerField(default=0)),
                ("conversations_processed", models.PositiveIntegerField(default=0)),
                ("conversations_total", models.PositiveIntegerField(default=0)),
                ("range_start_utc", models.DateTimeField()),
                ("range_end_utc", models.DateTimeField()),
                ("cancel_requested", models.BooleanField(default=False)),
                ("s3_build_key", models.CharField(blank=True, max_length=512, null=True)),
                ("s3_state_key", models.CharField(blank=True, max_length=512, null=True)),
                ("failure_reason", models.TextField(blank=True, null=True)),
                ("triggered_by_actor", models.CharField(blank=True, max_length=255, null=True)),
                ("started_at", models.DateTimeField(default=improvements.utils.time.utc_now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="improvement_analysis_runs",
                        to="conversation_ms.project",
                    ),
                ),
            ],
            options={
                "db_table": "improvements_analysis_run",
            },
        ),
        migrations.CreateModel(
            name="ImprovementBacklogItem",
            fields=[
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("dimension_id", models.CharField(max_length=128)),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("behavior", "Behavior"),
                            ("knowledge", "Knowledge"),
                            ("technical", "Technical"),
                            ("custom", "Custom"),
                        ],
                        max_length=32,
                    ),
                ),
                ("title", models.CharField(max_length=512)),
                ("diagnosis", models.TextField()),
                ("suggested_solution", models.JSONField(blank=True, default=dict)),
                ("affected_conversations_count", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("ignored", "Ignored"),
                            ("resolved", "Resolved"),
                            ("superseded", "Superseded"),
                        ],
                        default="active",
                        max_length=32,
                    ),
                ),
                ("ignored_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("status_changed_by_actor", models.CharField(blank=True, max_length=255, null=True)),
                ("first_seen_at", models.DateTimeField(default=improvements.utils.time.utc_now)),
                ("last_updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "improvements_backlog_item",
            },
        ),
        migrations.CreateModel(
            name="ImprovementCustomMonitor",
            fields=[
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("behavior_description", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="improvement_custom_monitors",
                        to="conversation_ms.project",
                    ),
                ),
            ],
            options={
                "db_table": "improvements_custom_monitor",
            },
        ),
        migrations.CreateModel(
            name="ImprovementBacklogItemConversation",
            fields=[
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("confidence_score", models.FloatField(blank=True, null=True)),
                ("evidence", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "backlog_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="affected_conversations",
                        to="improvements.improvementbacklogitem",
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="improvement_backlog_item_links",
                        to="conversation_ms.conversation",
                    ),
                ),
            ],
            options={
                "db_table": "improvements_backlog_item_conversation",
            },
        ),
        migrations.AddField(
            model_name="improvementbacklogitem",
            name="custom_monitor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="backlog_items",
                to="improvements.improvementcustommonitor",
            ),
        ),
        migrations.AddField(
            model_name="improvementbacklogitem",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="improvement_backlog_items",
                to="conversation_ms.project",
            ),
        ),
        migrations.AddField(
            model_name="improvementbacklogitem",
            name="run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="backlog_items",
                to="improvements.improvementanalysisrun",
            ),
        ),
        migrations.CreateModel(
            name="ImprovementAnalysisBatch",
            fields=[
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("batch_id", models.CharField(max_length=255)),
                ("input_file_id", models.CharField(max_length=255)),
                ("endpoint", models.CharField(max_length=255)),
                ("n_requests", models.PositiveIntegerField()),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("position", models.SmallIntegerField(default=0)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batches",
                        to="improvements.improvementanalysisrun",
                    ),
                ),
            ],
            options={
                "db_table": "improvements_analysis_batch",
            },
        ),
        migrations.CreateModel(
            name="ImprovementRunConversation",
            fields=[
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "processing_status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("completed", "Completed"), ("failed", "Failed")],
                        default="pending",
                        max_length=32,
                    ),
                ),
                ("is_amazing_conversation", models.BooleanField(blank=True, null=True)),
                ("dimension_results", models.JSONField(blank=True, default=list)),
                ("retry_count", models.SmallIntegerField(default=0)),
                ("failure_reason", models.TextField(blank=True, null=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="improvement_run_conversations",
                        to="conversation_ms.conversation",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="run_conversations",
                        to="improvements.improvementanalysisrun",
                    ),
                ),
            ],
            options={
                "db_table": "improvements_run_conversation",
                "indexes": [
                    models.Index(fields=["run", "processing_status"], name="improvement_run_id_f6219a_idx"),
                    models.Index(fields=["conversation", "run"], name="improvement_convers_382a6c_idx"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="improvementrunconversation",
            constraint=models.UniqueConstraint(
                fields=("run", "conversation"), name="improvements_run_conversation_unique_run_conversation"
            ),
        ),
        migrations.AddIndex(
            model_name="improvementcustommonitor",
            index=models.Index(fields=["project", "is_active"], name="improvement_project_a255e5_idx"),
        ),
        migrations.AddIndex(
            model_name="improvementbacklogitemconversation",
            index=models.Index(fields=["backlog_item", "created_at"], name="improvement_backlog_014019_idx"),
        ),
        migrations.AddConstraint(
            model_name="improvementbacklogitemconversation",
            constraint=models.UniqueConstraint(
                fields=("backlog_item", "conversation"), name="improvements_backlog_item_conversation_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="improvementbacklogitem",
            index=models.Index(fields=["project", "status", "-last_updated_at"], name="improvement_project_fe5b59_idx"),
        ),
        migrations.AddIndex(
            model_name="improvementbacklogitem",
            index=models.Index(fields=["run", "dimension_id"], name="improvement_run_id_67329a_idx"),
        ),
        migrations.AddIndex(
            model_name="improvementbacklogitem",
            index=models.Index(fields=["project", "item_type"], name="improvement_project_747e3c_idx"),
        ),
        migrations.AddIndex(
            model_name="improvementanalysisrun",
            index=models.Index(fields=["project", "status"], name="improvement_project_d65afa_idx"),
        ),
        migrations.AddIndex(
            model_name="improvementanalysisrun",
            index=models.Index(fields=["project", "-target_date"], name="improvement_project_6e7a98_idx"),
        ),
        migrations.AddConstraint(
            model_name="improvementanalysisrun",
            constraint=models.UniqueConstraint(
                fields=("project", "triggered_on_date"), name="improvements_run_unique_project_triggered_on_date"
            ),
        ),
        migrations.AddConstraint(
            model_name="improvementanalysisbatch",
            constraint=models.UniqueConstraint(
                fields=("run", "batch_id"), name="improvements_batch_unique_run_batch_id"
            ),
        ),
    ]
