# Generated by Django 4.2.27 on 2026-01-08 14:19

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                ("uuid", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("contact_urn", models.CharField(blank=True, max_length=255, null=True)),
                ("external_id", models.CharField(blank=True, max_length=255, null=True)),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("has_chats_room", models.BooleanField(default=False)),
                ("contact_name", models.CharField(blank=True, max_length=255, null=True)),
                ("channel_uuid", models.UUIDField(blank=True, null=True)),
                ("nps", models.IntegerField(blank=True, null=True)),
                (
                    "csat",
                    models.CharField(
                        blank=True,
                        choices=[
                            (1, "Very unsatisfied"),
                            (2, "Unatisfied"),
                            (3, "Neutral"),
                            (4, "Satisfied"),
                            (5, "Very satisfied"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "resolution",
                    models.CharField(
                        choices=[
                            (0, "Resolved"),
                            (1, "Unresolved"),
                            (2, "In Progress"),
                            (3, "Unclassified"),
                            (4, "Has Chat Room"),
                        ],
                        default=2,
                        max_length=255,
                    ),
                ),
            ],
            options={
                "db_table": "intelligences_conversation",
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                ("uuid", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "projects_project",
            },
        ),
        migrations.CreateModel(
            name="ConversationMessages",
            fields=[
                (
                    "conversation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="messages_data",
                        serialize=False,
                        to="conversation_ms.conversation",
                    ),
                ),
                ("messages", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Conversation Messages",
                "verbose_name_plural": "Conversation Messages",
                "db_table": "intelligences_conversationmessages",
            },
        ),
        migrations.AddField(
            model_name="conversation",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="conversations", to="conversation_ms.project"
            ),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["project", "contact_urn", "start_date", "end_date", "channel_uuid"],
                name="intelligenc_project_fdb57e_idx",
            ),
        ),
    ]
