# Generated by Django 4.2.27 on 2026-02-11 11:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conversation_ms", "0002_topic_subtopic_conversationclassification"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="ticket_uuid",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
