# Generated by Django 4.2.27 on 2026-02-25 13:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conversation_ms", "0003_conversation_ticket_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="csat",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1", "Very unsatisfied"),
                    ("2", "Unatisfied"),
                    ("3", "Neutral"),
                    ("4", "Satisfied"),
                    ("5", "Very satisfied"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="resolution",
            field=models.CharField(
                choices=[
                    ("0", "Resolved"),
                    ("1", "Unresolved"),
                    ("2", "In Progress"),
                    ("3", "Unclassified"),
                    ("4", "Has Chat Room"),
                ],
                default="2",
                max_length=255,
            ),
        ),
    ]
