# Generated by Django 4.2.27 on 2026-03-03 19:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conversation_ms", "0004_alter_conversation_csat_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="csat",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1", "Very unsatisfied"),
                    ("2", "Unsatisfied"),
                    ("3", "Neutral"),
                    ("4", "Satisfied"),
                    ("5", "Very satisfied"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
