# Generated by Django 4.2.27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conversation_ms", "0005_alter_conversation_csat"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectCount",
            fields=[
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="project_count",
                        serialize=False,
                        to="conversation_ms.project",
                    ),
                ),
                ("conversation_count", models.IntegerField(default=0)),
                (
                    "threshold_notified",
                    models.BooleanField(
                        default=False,
                        help_text="True after a message was sent to AmazonMQ for blocking trial at threshold.",
                    ),
                ),
            ],
            options={
                "db_table": "conversation_ms_projectcount",
            },
        ),
    ]
