# Generated by Django 4.2.27 on 2026-07-03 17:16

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conversation_ms", "0006_project_timezone"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConversationArchiveBatch",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("started_at", models.DateTimeField()),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("enqueued_count", models.IntegerField(default=0)),
                ("dry_run", models.BooleanField()),
            ],
            options={
                "db_table": "conversation_ms_conversationarchivebatch",
            },
        ),
        migrations.CreateModel(
            name="ConversationArchiveRecord",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("conversation_uuid", models.UUIDField(unique=True)),
                ("project_uuid", models.UUIDField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In progress"),
                            ("ARCHIVED", "Archived"),
                            ("DELETED", "Deleted"),
                            ("FAILED", "Failed"),
                        ],
                        max_length=32,
                    ),
                ),
                ("s3_key", models.CharField(blank=True, max_length=512, null=True)),
                ("started_at", models.DateTimeField()),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("failed_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("errors", models.JSONField(blank=True, null=True)),
                ("content_sha256", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "batch",
                    models.ForeignKey(
                        db_column="batch_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="conversation_ms.conversationarchivebatch",
                    ),
                ),
            ],
            options={
                "db_table": "conversation_ms_conversationarchiverecord",
                "indexes": [models.Index(fields=["status", "project_uuid"], name="conversatio_status_42661d_idx")],
            },
        ),
        migrations.AddConstraint(
            model_name="conversationarchiverecord",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("status__in", ["ARCHIVED", "DELETED"]), _negated=True),
                    ("s3_key__isnull", False),
                    _connector="OR",
                ),
                name="archive_record_s3_key_when_persisted",
            ),
        ),
        migrations.AddConstraint(
            model_name="conversationarchiverecord",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("status__in", ["ARCHIVED", "DELETED"]), _negated=True),
                    ("archived_at__isnull", False),
                    _connector="OR",
                ),
                name="archive_record_archived_at_when_persisted",
            ),
        ),
        migrations.AddConstraint(
            model_name="conversationarchiverecord",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("status", "DELETED"), _negated=True), ("deleted_at__isnull", False), _connector="OR"
                ),
                name="archive_record_deleted_at_when_deleted",
            ),
        ),
        migrations.AddConstraint(
            model_name="conversationarchiverecord",
            constraint=models.CheckConstraint(
                check=models.Q(("status", "DELETED"), ("deleted_at__isnull", True), _connector="OR"),
                name="archive_record_deleted_at_only_when_deleted",
            ),
        ),
        migrations.AddConstraint(
            model_name="conversationarchiverecord",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("status", "FAILED"), _negated=True), ("failed_at__isnull", False), _connector="OR"
                ),
                name="archive_record_failed_at_when_failed",
            ),
        ),
        migrations.AddConstraint(
            model_name="conversationarchiverecord",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("status__in", ["DELETED", "FAILED"]), _negated=True),
                    ("finished_at__isnull", False),
                    _connector="OR",
                ),
                name="archive_record_finished_at_when_terminal",
            ),
        ),
        migrations.AddConstraint(
            model_name="conversationarchiverecord",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("status__in", ["PENDING", "IN_PROGRESS"]), _negated=True),
                    ("finished_at__isnull", True),
                    _connector="OR",
                ),
                name="archive_record_no_finished_at_while_active",
            ),
        ),
    ]
