# Generated by Django 4.2.27 on 2026-07-29 12:00

import uuid

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone

BACKFILL_BATCH_SIZE = 1000


def backfill_legacy_close_pipeline_records(apps, schema_editor):
    """
    Legacy assumed-complete stamp for terminal conversations.

    Inserts an all-done ClosePipelineRecord for every Conversation with
    resolution != IN_PROGRESS that does not already have a record.
    Idempotent: safe to re-run (skip existing PKs via ignore_conflicts).
    Intended to run under RunPython(..., atomic=False) so each batch
    autocommits instead of holding one giant transaction.
    """
    Conversation = apps.get_model("conversation_ms", "Conversation")
    ClosePipelineRecord = apps.get_model("conversation_ms", "ClosePipelineRecord")

    now = timezone.now()
    batch = []
    qs = (
        Conversation.objects.exclude(resolution="2")
        .exclude(uuid__in=ClosePipelineRecord.objects.values_list("conversation_id", flat=True))
        .order_by("uuid")
        .only("uuid", "end_date", "created_at")
        .iterator(chunk_size=BACKFILL_BATCH_SIZE)
    )
    for conversation in qs:
        stamped_at = conversation.end_date or conversation.created_at or now
        batch.append(
            ClosePipelineRecord(
                conversation_id=conversation.uuid,
                classify_status="done",
                classify_at=stamped_at,
                classify_reclaim_count=0,
                topics_status="done",
                topics_at=stamped_at,
                topics_reclaim_count=0,
                billing_status="done",
                billing_at=stamped_at,
                billing_reclaim_count=0,
                datalake_status="done",
                datalake_at=stamped_at,
                datalake_reclaim_count=0,
                datalake_classification_at=stamped_at,
                datalake_topics_at=stamped_at,
            )
        )
        if len(batch) >= BACKFILL_BATCH_SIZE:
            ClosePipelineRecord.objects.bulk_create(batch, ignore_conflicts=True)
            batch.clear()

    if batch:
        ClosePipelineRecord.objects.bulk_create(batch, ignore_conflicts=True)


def noop_reverse(apps, schema_editor):
    # Keep legacy stamps if rolling back constraints/code; do not delete records.
    pass


class Migration(migrations.Migration):
    # Allow RunPython backfill to autocommit per statement; avoid one giant txn.
    atomic = False

    dependencies = [
        ("conversation_ms", "0006_project_timezone"),
    ]

    operations = [
        migrations.CreateModel(
            name="CloseDatalakeOutbox",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_kind",
                    models.CharField(
                        choices=[
                            ("classification", "Classification"),
                            ("topics", "Topics"),
                        ],
                        help_text="Datalake event kind: classification or topics.",
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Set when external publish is considered successful.",
                        null=True,
                    ),
                ),
                (
                    "last_error",
                    models.TextField(
                        blank=True,
                        help_text="Last publish failure detail for this event kind.",
                        null=True,
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        help_text="Conversation this datalake intent belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="close_datalake_outbox",
                        to="conversation_ms.conversation",
                    ),
                ),
            ],
            options={
                "db_table": "conversation_ms_closedatalakeoutbox",
            },
        ),
        migrations.CreateModel(
            name="ClosePipelineRecord",
            fields=[
                (
                    "conversation",
                    models.OneToOneField(
                        help_text="Conversation owned by this close-pipeline control-plane row.",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="close_pipeline",
                        serialize=False,
                        to="conversation_ms.conversation",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "classify_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pending", "Pending"),
                            ("done", "Done"),
                            ("skipped", "Skipped"),
                            ("failed", "Failed"),
                            ("dead", "Dead"),
                        ],
                        help_text="Classify (resolution) stage status.",
                        max_length=16,
                        null=True,
                    ),
                ),
                ("classify_at", models.DateTimeField(blank=True, null=True)),
                ("classify_pending_at", models.DateTimeField(blank=True, null=True)),
                ("classify_error", models.TextField(blank=True, null=True)),
                (
                    "classify_reclaim_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Automatic drain reclaim budget consumed for classify.",
                    ),
                ),
                (
                    "topics_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pending", "Pending"),
                            ("done", "Done"),
                            ("skipped", "Skipped"),
                            ("failed", "Failed"),
                            ("dead", "Dead"),
                        ],
                        help_text="Topics classification stage status.",
                        max_length=16,
                        null=True,
                    ),
                ),
                ("topics_at", models.DateTimeField(blank=True, null=True)),
                ("topics_pending_at", models.DateTimeField(blank=True, null=True)),
                ("topics_error", models.TextField(blank=True, null=True)),
                (
                    "topics_reclaim_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Automatic drain reclaim budget consumed for topics.",
                    ),
                ),
                (
                    "billing_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pending", "Pending"),
                            ("done", "Done"),
                            ("skipped", "Skipped"),
                            ("failed", "Failed"),
                            ("dead", "Dead"),
                        ],
                        help_text="Billing SQS publish stage status.",
                        max_length=16,
                        null=True,
                    ),
                ),
                ("billing_at", models.DateTimeField(blank=True, null=True)),
                ("billing_pending_at", models.DateTimeField(blank=True, null=True)),
                ("billing_error", models.TextField(blank=True, null=True)),
                (
                    "billing_reclaim_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Automatic drain reclaim budget consumed for billing.",
                    ),
                ),
                (
                    "datalake_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pending", "Pending"),
                            ("done", "Done"),
                            ("skipped", "Skipped"),
                            ("failed", "Failed"),
                            ("dead", "Dead"),
                        ],
                        help_text="Datalake events stage status.",
                        max_length=16,
                        null=True,
                    ),
                ),
                ("datalake_at", models.DateTimeField(blank=True, null=True)),
                ("datalake_pending_at", models.DateTimeField(blank=True, null=True)),
                ("datalake_error", models.TextField(blank=True, null=True)),
                (
                    "datalake_reclaim_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Automatic drain reclaim budget consumed for datalake.",
                    ),
                ),
                (
                    "datalake_classification_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Set once when conversation_classification datalake event is published.",
                        null=True,
                    ),
                ),
                (
                    "datalake_topics_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Set once when topics datalake event is published.",
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "conversation_ms_closepipelinerecord",
                "indexes": [
                    models.Index(
                        condition=models.Q(("classify_status__in", ["pending", "failed"])),
                        fields=["classify_status", "classify_pending_at"],
                        name="cpipe_classify_drain_idx",
                    ),
                    models.Index(
                        condition=models.Q(("topics_status__in", ["pending", "failed"])),
                        fields=["topics_status", "topics_pending_at"],
                        name="cpipe_topics_drain_idx",
                    ),
                    models.Index(
                        condition=models.Q(("billing_status__in", ["pending", "failed"])),
                        fields=["billing_status", "billing_pending_at"],
                        name="cpipe_billing_drain_idx",
                    ),
                    models.Index(
                        condition=models.Q(("datalake_status__in", ["pending", "failed"])),
                        fields=["datalake_status", "datalake_pending_at"],
                        name="cpipe_datalake_drain_idx",
                    ),
                    models.Index(
                        condition=models.Q(("classify_status", "dead")),
                        fields=["classify_status"],
                        name="cpipe_classify_dead_idx",
                    ),
                    models.Index(
                        condition=models.Q(("topics_status", "dead")),
                        fields=["topics_status"],
                        name="cpipe_topics_dead_idx",
                    ),
                    models.Index(
                        condition=models.Q(("billing_status", "dead")),
                        fields=["billing_status"],
                        name="cpipe_billing_dead_idx",
                    ),
                    models.Index(
                        condition=models.Q(("datalake_status", "dead")),
                        fields=["datalake_status"],
                        name="cpipe_datalake_dead_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="closedatalakeoutbox",
            index=models.Index(
                condition=models.Q(("published_at__isnull", True)),
                fields=["created_at"],
                name="cdl_outbox_unpub_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="closedatalakeoutbox",
            constraint=models.UniqueConstraint(
                fields=("conversation", "event_kind"),
                name="cdl_outbox_conv_event_uniq",
            ),
        ),
        migrations.RunPython(
            backfill_legacy_close_pipeline_records,
            noop_reverse,
            atomic=False,
        ),
        migrations.AddConstraint(
            model_name="closepipelinerecord",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("classify_at__isnull", True),
                        ("classify_error__isnull", True),
                        ("classify_pending_at__isnull", True),
                        ("classify_status__isnull", True),
                    ),
                    models.Q(
                        ("classify_at__isnull", True),
                        ("classify_error__isnull", True),
                        ("classify_pending_at__isnull", False),
                        ("classify_status", "pending"),
                    ),
                    models.Q(
                        ("classify_at__isnull", False),
                        ("classify_error__isnull", True),
                        ("classify_pending_at__isnull", True),
                        ("classify_status", "done"),
                    ),
                    models.Q(
                        ("classify_at__isnull", False),
                        ("classify_error__isnull", True),
                        ("classify_pending_at__isnull", True),
                        ("classify_status", "skipped"),
                    ),
                    models.Q(
                        ("classify_at__isnull", True),
                        ("classify_error__isnull", False),
                        ("classify_pending_at__isnull", True),
                        ("classify_status", "failed"),
                        models.Q(("classify_error", ""), _negated=True),
                    ),
                    models.Q(
                        ("classify_at__isnull", True),
                        ("classify_error__isnull", False),
                        ("classify_pending_at__isnull", True),
                        ("classify_status", "dead"),
                        models.Q(("classify_error", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="cpipe_classify_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="closepipelinerecord",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("topics_at__isnull", True),
                        ("topics_error__isnull", True),
                        ("topics_pending_at__isnull", True),
                        ("topics_status__isnull", True),
                    ),
                    models.Q(
                        ("topics_at__isnull", True),
                        ("topics_error__isnull", True),
                        ("topics_pending_at__isnull", False),
                        ("topics_status", "pending"),
                    ),
                    models.Q(
                        ("topics_at__isnull", False),
                        ("topics_error__isnull", True),
                        ("topics_pending_at__isnull", True),
                        ("topics_status", "done"),
                    ),
                    models.Q(
                        ("topics_at__isnull", False),
                        ("topics_error__isnull", True),
                        ("topics_pending_at__isnull", True),
                        ("topics_status", "skipped"),
                    ),
                    models.Q(
                        ("topics_at__isnull", True),
                        ("topics_error__isnull", False),
                        ("topics_pending_at__isnull", True),
                        ("topics_status", "failed"),
                        models.Q(("topics_error", ""), _negated=True),
                    ),
                    models.Q(
                        ("topics_at__isnull", True),
                        ("topics_error__isnull", False),
                        ("topics_pending_at__isnull", True),
                        ("topics_status", "dead"),
                        models.Q(("topics_error", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="cpipe_topics_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="closepipelinerecord",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("billing_at__isnull", True),
                        ("billing_error__isnull", True),
                        ("billing_pending_at__isnull", True),
                        ("billing_status__isnull", True),
                    ),
                    models.Q(
                        ("billing_at__isnull", True),
                        ("billing_error__isnull", True),
                        ("billing_pending_at__isnull", False),
                        ("billing_status", "pending"),
                    ),
                    models.Q(
                        ("billing_at__isnull", False),
                        ("billing_error__isnull", True),
                        ("billing_pending_at__isnull", True),
                        ("billing_status", "done"),
                    ),
                    models.Q(
                        ("billing_at__isnull", False),
                        ("billing_error__isnull", True),
                        ("billing_pending_at__isnull", True),
                        ("billing_status", "skipped"),
                    ),
                    models.Q(
                        ("billing_at__isnull", True),
                        ("billing_error__isnull", False),
                        ("billing_pending_at__isnull", True),
                        ("billing_status", "failed"),
                        models.Q(("billing_error", ""), _negated=True),
                    ),
                    models.Q(
                        ("billing_at__isnull", True),
                        ("billing_error__isnull", False),
                        ("billing_pending_at__isnull", True),
                        ("billing_status", "dead"),
                        models.Q(("billing_error", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="cpipe_billing_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="closepipelinerecord",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("datalake_at__isnull", True),
                        ("datalake_error__isnull", True),
                        ("datalake_pending_at__isnull", True),
                        ("datalake_status__isnull", True),
                    ),
                    models.Q(
                        ("datalake_at__isnull", True),
                        ("datalake_error__isnull", True),
                        ("datalake_pending_at__isnull", False),
                        ("datalake_status", "pending"),
                    ),
                    models.Q(
                        ("datalake_at__isnull", False),
                        ("datalake_error__isnull", True),
                        ("datalake_pending_at__isnull", True),
                        ("datalake_status", "done"),
                    ),
                    models.Q(
                        ("datalake_at__isnull", False),
                        ("datalake_error__isnull", True),
                        ("datalake_pending_at__isnull", True),
                        ("datalake_status", "skipped"),
                    ),
                    models.Q(
                        ("datalake_at__isnull", True),
                        ("datalake_error__isnull", False),
                        ("datalake_pending_at__isnull", True),
                        ("datalake_status", "failed"),
                        models.Q(("datalake_error", ""), _negated=True),
                    ),
                    models.Q(
                        ("datalake_at__isnull", True),
                        ("datalake_error__isnull", False),
                        ("datalake_pending_at__isnull", True),
                        ("datalake_status", "dead"),
                        models.Q(("datalake_error", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="cpipe_datalake_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="closepipelinerecord",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("datalake_at__isnull", True),
                        ("datalake_error__isnull", True),
                        ("datalake_pending_at__isnull", True),
                        ("datalake_status__isnull", True),
                        _negated=True,
                    ),
                    models.Q(
                        ("datalake_classification_at__isnull", True),
                        ("datalake_topics_at__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="cpipe_dl_unset_no_ev_ats",
            ),
        ),
        migrations.AddConstraint(
            model_name="closepipelinerecord",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("datalake_classification_at__isnull", True),
                    ("datalake_topics_at__isnull", True),
                    models.Q(
                        ("datalake_status__in", ["done", "skipped"]),
                        ("datalake_at__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="cpipe_dl_both_ev_imply_done",
            ),
        ),
        migrations.AddConstraint(
            model_name="closepipelinerecord",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("topics_status__isnull", True),
                        ("billing_status__isnull", True),
                        ("datalake_status__isnull", True),
                    ),
                    ("classify_status__in", ["done", "skipped"]),
                    _connector="OR",
                ),
                name="cpipe_down_needs_classify",
            ),
        ),
        migrations.AddConstraint(
            model_name="closepipelinerecord",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("classify_status__in", ["done", "skipped"]),
                        _negated=True,
                    ),
                    models.Q(
                        ("topics_status__isnull", False),
                        ("billing_status__isnull", False),
                        ("datalake_status__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="cpipe_classify_sets_down",
            ),
        ),
    ]
