# Generated by Django 4.2.27 on 2026-09-09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conversation_ms", "0007_close_pipeline_record"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE intelligences_conversation "
                        "ADD COLUMN has_conversation_starter boolean DEFAULT false NOT NULL"
                    ),
                    reverse_sql=(
                        "ALTER TABLE intelligences_conversation "
                        "DROP COLUMN has_conversation_starter"
                    ),
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="conversation",
                    name="has_conversation_starter",
                    field=models.BooleanField(default=False),
                ),
            ],
        ),
    ]
