# Generated by Django 4.2.27 on 2026-09-09

from django.db import migrations, models

INDEX_NAME = "conv_proj_starter_created_idx"
TABLE_NAME = "intelligences_conversation"


def create_conversation_starter_index(apps, schema_editor):
    concurrently = " CONCURRENTLY" if schema_editor.connection.vendor == "postgresql" else ""
    schema_editor.execute(
        f"CREATE INDEX{concurrently} {INDEX_NAME} ON {TABLE_NAME} "
        "(project_id, has_conversation_starter, created_at DESC, uuid DESC)"
    )


def drop_conversation_starter_index(apps, schema_editor):
    concurrently = " CONCURRENTLY" if schema_editor.connection.vendor == "postgresql" else ""
    schema_editor.execute(f"DROP INDEX{concurrently} IF EXISTS {INDEX_NAME}")


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("conversation_ms", "0010_conversation_has_conversation_starter"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    create_conversation_starter_index,
                    reverse_code=drop_conversation_starter_index,
                ),
            ],
            state_operations=[
                migrations.AddIndex(
                    model_name="conversation",
                    index=models.Index(
                        fields=["project", "has_conversation_starter", "-created_at", "-uuid"],
                        name=INDEX_NAME,
                    ),
                ),
            ],
        ),
    ]
